### PR TITLE
Bg add categories

### PR DESCRIPTION
**Pull request by cbgriffith**
# Description

Created a form for adding categories. Also edited the nav to include a link to Categories.  Edit and delete do not work currently.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. Clone down the repository.
2. `git fetch -a`
3. `git checkout bg-AddCategories`
4. Navigate to the root directory for this repo (directory-to)/tabloidmvc-the-daily-debuggers
5. Start TabloidMVC.sln
6. Make sure your db is created with seed data. Run [01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-daily-debuggers/blob/main/SQL/01_TabloidMVC_Create_DB.sql) and [02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-5/tabloidmvc-the-daily-debuggers/blob/main/SQL/02_TabloidMVC_Seed_Data.sql) queries in Visual Studio.
7. Start the server.
8. Log in as admin [admin@example.com](mailto:admin@example.com) (if not already logged in as admin).
9. Click Categories at the top of the page. 
10. Click New Category and you will be linked to a form for adding a new category.
11. Add Test to the name field and click create.
12. You should now see a list of categories,  There will be exactly 14 total.  Scroll to the very bottom of the list and you will see the new category you created with an id of 14 and a name of Test.
13. If you would like to further test this or test it through a SQL query, create a query for the database called TabloidMVC.  In your new query type: `Select * From Category` and run it.  This will show the full of the categories ordered by Id rather than alphabetical as seen from the web browser.  Look to make sure there's an entry of id 14 and a name of Test.
14. ???
15. PROFIT

***Edit and Delete do not work at this time***

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
Please include the branch name and instructions on fetching the branch as a reference in your testing instructions. 
Please either include the category names that should be seen or a SQL query that would give you the same result as you would test.

**Comment by sarahebrooks12** [comment]
In the example:
After making sure you have our repo cloned down into a local repository, git fetch --all in the master branch to retrieve this branch named sm-productTypeBranch that I have pushed up.

git checkout sm-productTypeBranch to switch to my branch and open up Visual Studio

Want to see something like this in your test instructions. While we know how to do this when you are in the field, there will more than likely be a dedicated test team that will not have that information memorized or maybe readily available. Better to overexplain than underexplain.

**Comment by sarahebrooks12** [comment]
👼

**Comment by nicholasvperry** [comment]
Add categories is working flawlessly.

**Review by andy-birt — APPROVED** [review]
🐮 🔔

**Pull request merged**
